// lib/font-templates.ts
import { FontTemplate } from "./types";

export const FONT_TEMPLATES: FontTemplate[] = [
  {
    id: "gradient-1",
    name: "Gradient Text",
    description: "Animated gradient text display",
    fontFamily: "Poppins, sans-serif",
    settings: {
      fontSize: 48,
      fontWeight: 800,
      gradientColors: ["#40ffaa", "#4079ff", "#40ffaa", "#4079ff"],
      animationSpeed: 3,
      showBorder: false,
      isBold: true,
      isItalic: false,
      isUnderline: false,
      textStroke: 0,
      textStrokeColor: "#000000",
      textAlign: "center",
      animationDelay: 70,
      animationDuration: 1.5,
      animationEase: "power3.out",
      splitType: "chars",
    },
  },
  {
    id: "showgirl-1",
    name: "ShowGirl Neon Blink",
    description: "Neon blinking retro-style text",
    fontFamily: "Showgirl, cursive",
    settings: {
      fontSize: 48,
      fontWeight: 400,
      gradientColors: ["#ff4444", "#ff4444"],
      animationSpeed: 2,
      showBorder: false,
      isBold: false,
      isItalic: false,
      isUnderline: false,
      textStroke: 0,
      textStrokeColor: "#000000",
      textAlign: "center",
      animationDelay: 70,
      animationDuration: 1.5,
      animationEase: "power3.out",
      splitType: "chars",
    },
  },
  {
    id: "glowing-1",
    name: "Glowing Text",
    description: "Sequential glowing animation for each character",
    fontFamily: "Arial Black, sans-serif",
    settings: {
      fontSize: 48,
      fontWeight: 700,
      gradientColors: ["#00ffff", "#ffff00", "#ff6347"],
      animationSpeed: 2,
      showBorder: false,
      isBold: true,
      isItalic: false,
      isUnderline: false,
      textStroke: 0,
      textStrokeColor: "#000000",
      textAlign: "center",
      animationDelay: 70,
      animationDuration: 1.5,
      animationEase: "power3.out",
      splitType: "chars",
    },
  },
  {
    id: "neonspotlight-1",
    name: "Neon Spotlight",
    description: "Spotlight neon gradient scan animation",
    fontFamily: "Orbitron, sans-serif",
    settings: {
      fontSize: 48,
      fontWeight: 700,
      gradientColors: ["#ff0000", "#ffff66", "#00ff66"],
      animationSpeed: 5,
      showBorder: false,
      isBold: true,
      isItalic: false,
      isUnderline: false,
      textStroke: 0,
      textStrokeColor: "#000000",
      textAlign: "center",
      animationDelay: 70,
      animationDuration: 1.5,
      animationEase: "power3.out",
      splitType: "chars",
    },
  },
];
